#!/bin/bash

echo "🚀 Sachel Git TUI Demo"
echo "====================="
echo ""
echo "This will launch the Sachel Git Terminal User Interface."
echo "Use the following keyboard shortcuts:"
echo ""
echo "📋 Leader Key Commands (Space + ...):"
echo "  Space → g → s  : Git Status view"
echo "  Space → g → c  : Commit view"
echo "  Space → g → d  : Diff view"
echo "  Space → h      : Help/keybinding overview"
echo "  Space → q      : Quit"
echo ""
echo "🔧 In Status View:"
echo "  j/k    : Navigate up/down through files"
echo "  s      : Stage file"
echo "  u      : Unstage file"
echo "  Enter  : View diff"
echo "  r      : Refresh"
echo ""
echo "🔧 In Diff View:"
echo "  j/k    : Navigate between hunks"
echo "  J/K    : Navigate between files"
echo "  s      : Stage current hunk"
echo "  u      : Unstage current hunk"
echo "  v      : Enter line selection mode"
echo "  Tab    : Toggle staged/unstaged view"
echo ""
echo "🔧 In Commit View:"
echo "  i         : Enter insert mode"
echo "  Esc       : Exit insert mode"
echo "  Ctrl+C    : Create commit"
echo "  Ctrl+A    : Amend last commit"
echo ""
echo "Press Enter to launch the demo..."
read

echo "Launching Sachel Git..."
./.build/debug/sachel